import type { Metadata } from "next";
import "./globals.css";
import {routing} from '@/i18n/routing';
 
export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export const metadata: Metadata = {
  title: "Moontajty",
  description: "Generated by create Team moontajty",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/Moontajty_dark.png" type="image/x-icon" sizes="32x32"/>
      </head>
      <body>{children}</body>
    </html>
  );
}