import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Moontajty",
  description: "Generated by create Team moontajty",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/Moontajty_dark.png" type="image/x-icon" sizes="32x32"/>
      </head>
      <body>{children}</body>
    </html>
  );
}